### ISSUE TITLE
Intialize Failed, Any solution ?

### ISSUE THREAD

**Issue by saimanoj18** [NatanBiesmans/lms5xx#1]
Hello,

I have tried your driver, however, I was repeatedly getting this error._
Specifically, I m getting this error

```
iirav@iirav:~$ rosrun laser_node laser_node 
	*** Attempting to initialize the Sick LMS 5xx...
	Attempting to connect to Sick LMS 5xx @ 192.168.0.1:2111
A Timeout Occurred - SickLMS5xx::_setupConnection: select() timeout!
A Timeout Occurred - SickLMS5xx::_setupConnection: select() timeout!
[ERROR] [1496664746.220065882]: Initialize failed!

```

I also tried, setting one of the ethernet port to 192.168.0.10, but still ending up with the same error.

Could you help ?

**Comment by NatanBiesmans** [comment]
A good practice is to first try and connect with the standard sick tools. You can find them on their website. If this is working without any hickups we know there aren't any network issues. (unless you have differences in the config between OS'es.) 

Check if you can give it an arbitrary ip-address and port, and see if this works. (as a means for debugging)

**Comment by saimanoj18** [comment]
I tried using SOPAS, standard sick laser scanner tool to work on WINDOWS and still the device is not getting detected. I have seen some online videos, which show that the device gets detected automatically by this software. However, I m having difficulty at that point itself!

**Comment by NatanBiesmans** [comment]
This is then not an issue of this driver.

I would suggest resetting the LIDAR. 

I would recommend to contact SICK should your problem persist.

**Comment by saimanoj18** [comment]
Yes, I ll do that

**Comment by ans-qureshi** [comment]
@saimanoj18 hi did you solve this issue? I'd like to know how. Thanks!
